### ISSUE TITLE
Avoid duplicate question simulations

### ISSUE THREAD

**Issue by bowl-of-rais** [d-isasterhub/IDP-simulated-user-exp#3]
We want to have only one LLM-generated answer per simulated user and question and run.

- [x] reconsider defaultdicts as a data structure?
- [x] for now: skip questions that are already simulated

**Comment by d-isasterhub** [comment]
I think we might want to use the actual user ids instead of relying on the order of the original dataset (as it is currently done).

This means, we need to update the current results table with the actual user id as well.
